version: '3.8'

services:
  authservice:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    container_name: authservice
    ports:
      - "8000:8000" # Replace with your authservice port
    env_file:
      - ./AuthService/.env
    networks:
      - app_network

  otpservice:
    build:
      context: ./OtpService
      dockerfile: Dockerfile
    container_name: otpservice
    ports:
      - "8001:8001" # Replace with your otpservice port
    env_file:
      - ./OtpService/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - redis
      - kafka
    networks:
      - app_network
    restart: always

  mailservice:
    build:
      context: ./MailService
      dockerfile: Dockerfile
    container_name: mailservice
    ports:
      - "8002:8002" # Replace with your mailservice port
    env_file:
      - ./MailService/.env
    depends_on:
      - otpservice
    networks:
      - app_network
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092" # Kafka client communication
      - "9093:9093" # Kafka controller communication
    environment:
      - KAFKA_KRAFT_MODE=true
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LOG_RETENTION_HOURS=168
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - CLUSTER_ID=Mk3OEYBSD34fcwNTJENDM2Ql
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/var/lib/kafka/data
    networks:
      - app_network

volumes:
  kafka-data:

networks:
  app_network:
    driver: bridge
